FROM debian:bullseye
# GLIBC 2.31, same as Ubuntu 20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get install -y \
    build-essential \
    cmake \
    git \
    ninja-build \
    python3
