stages:
  - build
  - publish

variables:
  LINUX_BUILDER: "registry.cn-beijing.aliyuncs.com/iflyos-service/linux-builder:latest"
  LPM_REGISTRY: "https://integration-registry-lpm.listenai.com"

build-win32:
  stage: build
  script: cmd.exe /c 'chcp 437 && build.bat && cp out\cskburn\Release\cskburn.exe cskburn-win32.exe'
  artifacts:
    paths:
      - cskburn-win32.exe
  tags:
    - csk_builder

build-linux:
  stage: build
  script: |
    docker pull ${LINUX_BUILDER}
    docker run --rm -v ${PWD}:/project ${LINUX_BUILDER} bash -c './build.sh'
    docker rmi ${LINUX_BUILDER}
    cp out/cskburn/cskburn cskburn-linux
  artifacts:
    paths:
      - cskburn-linux
  tags:
    - iflyos-builder

bundle:
  stage: publish
  script: echo
  artifacts:
    paths:
      - cskburn-win32.exe
      - cskburn-linux
  tags:
    - iflyos-builder

publish:
  stage: publish
  script: |
    docker run --rm \
      -v ${PWD}:/project \
      -e LPMRC="${LPMRC}" \
      -e LPM_REGISTRY="${LPM_REGISTRY}" \
      node:lts \
      bash -c 'cd /project && ./publish.sh'
  tags:
    - iflyos-builder
