stages:
  - build
  - publish

variables:
  LINUX_BUILDER: "registry.cn-beijing.aliyuncs.com/iflyos-service/linux-builder:latest"

before_script:
  - git submodule update --init

build:win32-x64:
  stage: build
  script: cmd.exe /c 'chcp 437 && build.bat && cp out\cskburn\Release\cskburn.exe cskburn-win32-x64.exe'
  artifacts:
    paths:
      - cskburn-win32-x64.exe
  tags:
    - csk_builder

build:linux-x64:
  stage: build
  script: |
    docker build -f Dockerfile.debian -t cskburn-debian .
    docker run --rm -v $PWD:/project cskburn-debian ./test.sh
    cp out/cskburn/cskburn cskburn-linux-x64
  artifacts:
    paths:
      - cskburn-linux-x64
  tags:
    - iflyos-builder

build:linux-x64-musl:
  stage: build
  script: |
    docker build -f Dockerfile.alpine -t cskburn-alpine .
    docker run --rm -v $PWD:/project cskburn-alpine ./test.sh
    cp out/cskburn/cskburn cskburn-linux-x64-musl
  artifacts:
    paths:
      - cskburn-linux-x64-musl
  tags:
    - iflyos-builder

build:linux-arm:
  stage: build
  script: |
    docker build -f Dockerfile.debian -t cskburn-debian .
    docker run --rm --user $(id -u gitlab-runner):$(id -g gitlab-runner) -v $PWD:/project cskburn-debian ./test.sh
    cp out/cskburn/cskburn cskburn-linux-arm
  artifacts:
    paths:
      - cskburn-linux-arm
  tags:
    - rpi4b

build:linux-arm-musl:
  stage: build
  script: |
    docker build -f Dockerfile.alpine -t cskburn-alpine .
    docker run --rm --user $(id -u gitlab-runner):$(id -g gitlab-runner) -v $PWD:/project cskburn-alpine ./test.sh
    cp out/cskburn/cskburn cskburn-linux-arm-musl
  artifacts:
    paths:
      - cskburn-linux-arm-musl
  tags:
    - rpi4b

bundle:
  stage: publish
  script: echo
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}"
    paths:
      - cskburn-win32-x64.exe
      - cskburn-linux-x64
      - cskburn-linux-x64-musl
      - cskburn-linux-arm
      - cskburn-linux-arm-musl
  tags:
    - iflyos-builder

publish-lpm:
  stage: publish
  when: manual
  only:
    refs:
      - tags
  script: |
    docker run --rm \
      -v ${PWD}:/project \
      -e NPMRC="" \
      -e NPM_CONFIG_REGISTRY="${LPM_REGISTRY}" \
      -e NPM_CONFIG_USERNAME="xychen" \
      -e NPM_CONFIG_EMAIL="xychen@listenai.com" \
      -e NPM_CONFIG__PASSWORD="${LPM_TOKEN}" \
      -e PKG_NAME="@tool/cskburn" \
      -e PKG_VERSION="${CI_COMMIT_REF_NAME}" \
      node:lts \
      bash -c 'cd /project && ./publish.sh'
  tags:
    - iflyos-builder

publish-npm:
  stage: publish
  when: manual
  only:
    refs:
      - tags
  script: |
    docker run --rm \
      -v ${PWD}:/project \
      -e NPMRC="//registry.npmjs.org/:_authToken=${NPM_TOKEN}" \
      -e PKG_NAME="@listenai/cskburn" \
      -e PKG_VERSION="${CI_COMMIT_REF_NAME}" \
      node:lts \
      bash -c 'cd /project && ./publish.sh'
  tags:
    - iflyos-builder
