stages:
  - build
  - publish

variables:
  LINUX_BUILDER: "registry.cn-beijing.aliyuncs.com/iflyos-service/linux-builder:latest"

build:win32-x64:
  stage: build
  script: cmd.exe /c 'chcp 437 && build.bat && cp out\cskburn\Release\cskburn.exe cskburn-win32-x64.exe'
  artifacts:
    paths:
      - cskburn-win32-x64.exe
  tags:
    - csk_builder

build:linux-x64:
  stage: build
  script: |
    docker pull ${LINUX_BUILDER}
    docker run --rm -v ${PWD}:/project ${LINUX_BUILDER} bash -c './build.sh'
    cp out/cskburn/cskburn cskburn-linux-x64
  artifacts:
    paths:
      - cskburn-linux-x64
  tags:
    - iflyos-builder

build:linux-arm:
  stage: build
  script: |
    ./build.sh
    cp out/cskburn/cskburn cskburn-linux-arm
  artifacts:
    paths:
      - cskburn-linux-arm
  tags:
    - rpi4b

build:darwin-x64:
  stage: build
  script: |
    export CMAKE_PREFIX_PATH=/usr/local
    ./build.sh
    cp out/cskburn/cskburn cskburn-darwin-x64
  artifacts:
    paths:
      - cskburn-darwin-x64
  tags:
    - ios

bundle:
  stage: publish
  script: echo
  artifacts:
    paths:
      - cskburn-win32-x64.exe
      - cskburn-linux-x64
      - cskburn-linux-arm
      - cskburn-darwin-x64
  tags:
    - iflyos-builder

publish-lpm:
  stage: publish
  when: manual
  only:
    refs:
      - tags
  script: |
    docker run --rm \
      -v ${PWD}:/project \
      -e NPMRC="" \
      -e NPM_CONFIG_REGISTRY="${LPM_REGISTRY}" \
      -e NPM_CONFIG_USERNAME="xychen" \
      -e NPM_CONFIG_EMAIL="xychen@listenai.com" \
      -e NPM_CONFIG__PASSWORD="${LPM_TOKEN}" \
      -e PKG_NAME="@tool/cskburn" \
      -e PKG_VERSION="${CI_COMMIT_REF_NAME}" \
      node:lts \
      bash -c 'cd /project && ./publish.sh'
  tags:
    - iflyos-builder

publish-npm:
  stage: publish
  when: manual
  only:
    refs:
      - tags
  script: |
    docker run --rm \
      -v ${PWD}:/project \
      -e NPMRC="//registry.npmjs.org/:_authToken=${NPM_TOKEN}" \
      -e PKG_NAME="@listenai/cskburn" \
      -e PKG_VERSION="${CI_COMMIT_REF_NAME}" \
      node:lts \
      bash -c 'cd /project && ./publish.sh'
  tags:
    - iflyos-builder
