FROM debian:buster

RUN mkdir -p /project
WORKDIR /project

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update

RUN apt-get install -y \
    build-essential \
    cmake \
    pkg-config

RUN apt-get install -y git libusb-1.0
