FROM alpine:3.11

RUN mkdir -p /project
WORKDIR /project

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && \
    apk update

RUN apk --no-cache add \
    bash \
    cmake \
    make \
    g++ \
    libtool \
    musl-dev \
    linux-headers \
    pkgconfig

RUN apk --no-cache add git libusb-dev
