FROM debian:buster

RUN mkdir -p /project
WORKDIR /project

ENV DEBIAN_FRONTEND=noninteractive
RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    sed -i 's|security.debian.org/debian-security|mirrors.ustc.edu.cn/debian-security|g' /etc/apt/sources.list && \
    apt-get update

RUN apt-get install -y \
    build-essential \
    cmake \
    pkg-config

RUN apt-get install -y git libusb-1.0
