FROM alpine:3.11

RUN mkdir -p /project
WORKDIR /project

RUN apk update

RUN apk --no-cache add \
    bash \
    cmake \
    make \
    g++ \
    libtool \
    musl-dev \
    linux-headers \
    pkgconfig

RUN apk --no-cache add git libusb-dev
