name: CMake build

inputs:
  shell:
    description: 'The shell to use'
    required: false
    default: bash
  build-dir:
    description: 'The build directory'
    required: false
    default: build
  build-config:
    description: 'The build configuration'
    required: false
    default: Release
  build-args:
    description: 'The build arguments'
    required: false
    default:

runs:
  using: composite
  steps:
    - run: |
        cmake -G Ninja -B ${{ inputs.build-dir }} ${{ inputs.build-args }}
        cmake --build ${{ inputs.build-dir }} --config ${{ inputs.build-config }}
      shell: ${{ inputs.shell }}
